language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
os: linux
env:
  global:
    - PINS="mirage-crypto.dev:. mirage-crypto-rng.dev:. mirage-crypto-rng-mirage.dev:. mirage-crypto-pk.dev:."
    - PACKAGE="mirage-crypto-pk"
    - TESTS=true
    - DISTRO=alpine
jobs:
  include:
  - name: OCaml 4.08 with mirage-xen
    arch: amd64
    env: OCAML_VERSION=4.08 DEPOPTS="zarith-xen mirage-xen-posix"
  - name: OCaml 4.10 on arm64
    arch: arm64
    env: OCAML_VERSION=4.10
  - name: OCaml 4.09 with freestanding on arm64
    arch: arm64
    env: OCAML_VERSION=4.09 DEPOPTS="zarith-freestanding ocaml-freestanding"
notifications:
  email: false
